export default {
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  SET_LOADING: "SET_LOADING",
};
